# Generated by Django 5.2.3 on 2025-06-17 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_guide', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='localguide',
            name='travelers',
            field=models.ManyToManyField(blank=True, related_name='guides_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
