# Generated by Django 5.2.3 on 2025-06-17 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_guide', '0002_localguide_travelers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localguide',
            options={},
        ),
        migrations.RenameField(
            model_name='localguide',
            old_name='address',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='localguide',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='localguide',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='localguide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='localguide',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='localguide',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='localguide',
            name='state',
        ),
        migrations.RemoveField(
            model_name='localguide',
            name='travelers',
        ),
        migrations.RemoveField(
            model_name='localguide',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='localguide',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='guide_profiles/'),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_guide', to=settings.AUTH_USER_MODEL),
        ),
    ]
