# Generated by Django 5.2.3 on 2025-06-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_guide', '0002_remove_localguide_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localguide',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='local_guide_cover_images/'),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='local_guide_images/'),
        ),
    ]
