# Generated by Django 5.2.3 on 2025-06-17 13:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_guide', '0003_alter_localguide_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localguide',
            options={'ordering': ['-created_at'], 'verbose_name': 'Local Guide', 'verbose_name_plural': 'Local Guides'},
        ),
        migrations.RenameField(
            model_name='localguide',
            old_name='bio',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='localguide',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='localguide',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('ON_VACATION', 'On Vacation')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='localguide',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='local_guide_cover_images/'),
        ),
        migrations.AddField(
            model_name='localguide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='local_guide_images/'),
        ),
        migrations.AddField(
            model_name='localguide',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='localguide',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localguide',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='localguide',
            name='travelers',
            field=models.ManyToManyField(blank=True, related_name='guides_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localguide',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='experience_years',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_guide_app_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
