# Generated by Django 5.2.3 on 2025-06-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_guide', '0004_alter_localguide_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localguide',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
