# Generated by Django 5.2.3 on 2025-06-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
