# Generated by Django 5.2.3 on 2025-06-18 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0002_branch_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(upload_to='website/blog/')),
                ('author_name', models.CharField(max_length=255)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='website/blog/authors/')),
                ('categories', models.CharField(blank=True, max_length=255, null=True)),
                ('post_format', models.CharField(choices=[('TEXT', 'Text'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('GALLERY', 'Gallery')], default='TEXT', max_length=20)),
                ('read_time', models.PositiveIntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='website/client_logos/')),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Logo',
                'verbose_name_plural': 'Client Logos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='website/hero_sliders/')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Travel Platform', max_length=255)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('hero_title', models.CharField(default='Are You Ready...', max_length=255)),
                ('hero_subtitle', models.CharField(default='To explore new things?', max_length=255)),
                ('explore_title', models.CharField(default='Explore more with us', max_length=255)),
                ('explore_description', models.TextField(default='Join 2000+ locals & 1200+ contributors from 3000 cities')),
                ('discount_title', models.CharField(default='Enjoy Your Holiday with 50% Discount', max_length=255)),
                ('discount_description', models.TextField(default='Nemo enim ipsam voluptatem quia voluptas sit aspernatur')),
                ('newsletter_title', models.CharField(default='Subscribe to Get Special Offers', max_length=255)),
                ('newsletter_description', models.CharField(default='Newsletter Sign up', max_length=255)),
                ('featured_in_title', models.CharField(default='We were featured in', max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_address', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='website/testimonials/')),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='website/activities/')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Top Activity',
                'verbose_name_plural': 'Top Activities',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PopularTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, max_length=50, null=True)),
                ('badge_type', models.CharField(blank=True, choices=[('BESTSELLER', 'Bestseller'), ('FEATURED', 'Featured'), ('NEW', 'New'), ('DISCOUNT', 'Discount')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_tours', to='agency.tourpackage')),
            ],
            options={
                'verbose_name': 'Popular Tour',
                'verbose_name_plural': 'Popular Tours',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
