# Generated by Django 5.2.3 on 2025-06-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_tourbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='hotels',
        ),
    ]
