# Generated by Django 5.2.3 on 2025-06-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_remove_tourpackage_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agency',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
