# Generated by Django 5.2.3 on 2025-06-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_agency_address_alter_agency_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='discount_price',
        ),
    ]
