# Generated by Django 5.2.3 on 2025-06-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('agency', 'agency'), ('local_guide', 'local_guide'), ('traveler', 'traveler')], default='buyer', max_length=50),
        ),
    ]
