# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignUpTraveller():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signUpTraveller(self):
    # Navigate to the home page
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1235, 675)
    
    # Click on Sign Up link
    self.driver.find_element(By.LINK_TEXT, "Sign Up").click()
    
    # Fill in the initial signup form
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("testRegistration@gmail.com")
    self.driver.find_element(By.ID, "id_password1").send_keys("123qweASD?")
    self.driver.find_element(By.ID, "id_password2").click()
    self.driver.find_element(By.ID, "id_password2").send_keys("123qweASD?")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lg").click()
    
    # Wait for the identification check page and select traveler
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.NAME, "user_type"))
    )
    
    # Select traveler option (assuming it's the third option)
    traveler_option = self.driver.find_element(By.CSS_SELECTOR, "input[name='user_type'][value='3']")
    traveler_option.click()
    
    # Submit the form
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    
    # Wait for the traveler profile completion form
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.ID, "id_full_name"))
    )
    
    # Fill in the traveler profile form
    self.driver.find_element(By.ID, "id_full_name").click()
    self.driver.find_element(By.ID, "id_full_name").send_keys("testTrveler")
    self.driver.find_element(By.ID, "id_phone_number").click()
    self.driver.find_element(By.ID, "id_phone_number").send_keys("034111111")
    self.driver.find_element(By.ID, "id_date_of_birth").click()
    self.driver.find_element(By.ID, "id_date_of_birth").send_keys("2000-01-18")
    self.driver.find_element(By.ID, "id_gender").click()
    dropdown = self.driver.find_element(By.ID, "id_gender")
    dropdown.find_element(By.XPATH, "//option[. = 'Male']").click()
    
    # Handle profile picture upload (skip for now to avoid file path issues)
    # self.driver.find_element(By.ID, "id_profile_picture").send_keys("C:\\fakepath\\test_image.jpg")
    
    self.driver.find_element(By.ID, "id_address").click()
    self.driver.find_element(By.ID, "id_address").send_keys("Skardu\\nkamanbagh p.o Mehdiabad")
    self.driver.find_element(By.ID, "id_city").send_keys("Skardu")
    self.driver.find_element(By.ID, "id_zip_code").send_keys("16100")
    self.driver.find_element(By.ID, "id_country").send_keys("Pakistan")
    self.driver.find_element(By.ID, "id_state").click()
    self.driver.find_element(By.ID, "id_state").send_keys("Pakistan")
    self.driver.find_element(By.ID, "id_passport_number").click()
    self.driver.find_element(By.ID, "id_passport_number").send_keys("123456789")
    self.driver.find_element(By.ID, "id_passport_expiry").click()
    self.driver.find_element(By.ID, "id_passport_expiry").send_keys("2025-08-20")
    self.driver.find_element(By.ID, "id_preferred_language").click()
    self.driver.find_element(By.ID, "id_preferred_language").send_keys("Urdu")
    self.driver.find_element(By.ID, "submit-id-submit").click()
  
