# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignUplocalGuide():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signUplocalGuide(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1235, 675)
    self.driver.find_element(By.LINK_TEXT, "Sign Up").click()
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("testlocalguide@gmail.com")
    self.driver.find_element(By.ID, "id_password1").click()
    self.driver.find_element(By.ID, "id_password1").send_keys("123qweASD?")
    self.driver.find_element(By.ID, "id_password2").click()
    self.driver.find_element(By.ID, "id_password2").send_keys("123qweASD?")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(2) .form-check-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "id_full_name").click()
    self.driver.find_element(By.ID, "id_full_name").send_keys("Wajahat Hussain")
    self.driver.find_element(By.ID, "id_phone").send_keys("03473171114")
    self.driver.find_element(By.ID, "id_city").send_keys("Skardu")
    self.driver.find_element(By.ID, "id_zip_code").send_keys("16100")
    self.driver.find_element(By.ID, "id_country").send_keys("Pakistan")
    self.driver.find_element(By.ID, "id_address").send_keys("Skardu\\nkamanbagh p.o Mehdiabad")
    self.driver.find_element(By.ID, "div_id_state").click()
    self.driver.find_element(By.ID, "id_state").click()
    self.driver.find_element(By.ID, "id_state").send_keys("Pakistan")
    self.driver.find_element(By.ID, "id_experience_years").click()
    self.driver.find_element(By.ID, "id_experience_years").send_keys("3")
    self.driver.find_element(By.ID, "id_availability").click()
    self.driver.find_element(By.ID, "id_image").click()
    self.driver.find_element(By.ID, "id_image").send_keys("C:\\fakepath\\waju.png")
    self.driver.find_element(By.CSS_SELECTOR, "#div_id_cover_image .form-control").click()
    self.driver.find_element(By.ID, "id_cover_image").click()
    self.driver.find_element(By.ID, "id_cover_image").send_keys("C:\\fakepath\\images.jpeg")
    self.driver.find_element(By.ID, "id_skills").click()
    self.driver.find_element(By.ID, "id_skills").send_keys("ABD")
    self.driver.find_element(By.ID, "submit-id-submit").click()
  
