# Generated by Django 5.2.3 on 2025-06-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_trips', to='traveler.traveler'),
        ),
    ]
